### ISSUE TITLE
Download file is corrupted

### ISSUE THREAD

**Issue by MarioSertorio** [headshot2017/supertux-switch#1]
To properly run the game, I had to first download Milestone 1 (Mar 7, 2022), copy the files to sdmc:/switch/, and then download the latest version.

If you just download the latest version and perform a clean install, it won't start.

I suppose the latest version is missing some files.

**Comment by headshot2017** [comment]
oh shit, you're right, i'll fix the release in a moment

**Comment by headshot2017** [comment]
should be fixed now
